spring:
  application:
    name: spring-cloud-config-server

  cloud:
    config:
      server:
        git:
          url: https://github.com/maduradevbit/git-config-repo



server:
  port: ${port:8888}



